[package]
name = "cutlass-sync-server"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.103"
automerge = "0.10.0"
futures-util = "0.3.32"
tokio = { version = "1.52.4", features = ["full"] }
tokio-tungstenite = "0.30.0"

[dev-dependencies]
cutlass-core = { path = "../cutlass-core" }
